#!/usr/bin/env make -f

install: build
	mv ../Tangoish_for_Rainlendar_by_ninique_jceb.zip ../Tangoish_for_Rainlendar_by_ninique_jceb.r2skin

build:
	zip -r ../Tangoish_for_Rainlendar_by_ninique_jceb.zip *
