"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"
# Documentation: https://docs.jj-vcs.dev/latest/config/

[user]
name = "Jan Christoph Ebersbach"
email = "jan-christoph.ebersbach@identinet.io"

[identity.default]
name = "Jan Christoph Ebersbach"
email = "jceb@e-jc.de"
signingkey = "444912B0B381009F"
[identity.ssi]
name = "Jan Christoph Ebersbach"
email = "jan-christoph.ebersbach@identinet.io"
signingkey = "444912B0B381009F"
[identity.eucon]
name = "Jan Christoph Ebersbach"
email = "jan.ebersbach@eucon.com"

[ui]
default-command = "status"
diff-formatter = ":git"
merge-editor = "vimdiff"

[signing]
behavior = "own"
backend = "gpg"

[colors]
"diff token" = { underline = false }

[lazyjj]
# https://github.com/Cretezy/lazyjj?tab=readme-ov-file#configuration
# highlight-color = "#323264"
highlight-color = "#b7c1e3"

[git]
sign-on-push = true

[remotes.origin]
auto-track-bookmarks = "*"

[fsmonitor]
backend = "watchman"
watchman.register-snapshot-trigger = true

[snapshot]
max-new-file-size = "10MiB"
# auto-update-stale = true # what does this do?

[templates]
# log_node = '''
# if(self && !current_working_copy && !immutable && !conflict && in_branch(self),
#   "◇",
#   builtin_log_node
# )
# '''

[template-aliases]
# hide non-important parts of the ID
'format_short_change_id(id)' = 'id.shortest()'
"in_branch(commit)" = 'commit.contained_in("immutable_heads()..bookmarks()")'

[revset-aliases]
# used to update bookmarks
'closest_bookmark(to)' = 'heads(::to & bookmarks())'

# Remove  untracked_remote_bookmarks() and replace it with just bookmarks("release") to make feature etc.
# branches/bookmarks editable
'immutable_heads()' = 'trunk() | tags() | bookmarks("release")'

[aliases]

# update git tag/bookmark to the latest change
# tug = ["bookmark", "move", "--from", "closest_bookmark(@-)", "--to", "@-"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]
rebase-all = ["rebase", "-s", "all:roots(trunk()..mutable())", "-d", "trunk()"]
rebase-main = ["rebase", "-d", "trunk()"]
# Github pull-request diff
diff-main = ["diff", "--from", "fork_point(trunk()|@)"]

# list all configuration options
config-all = ["config", "list", "--include-defaults"]

# b = ["bookmark"]
bc = ["bookmark", "create", "-r", "@-"]
bl = ["bookmark", "list"]
bs = ["bookmark", "set"]
bt = ["bookmark", "track"]
c = ["commit"]
ci = ["commit", "--interactive"]
d = ["diff"]
de = ["describe"]
dm = ["diff-main"]
e = ["edit"]
ee = ["edit", "@-"]
l = ["log", "-s"]
ll = ["log", "-s", "-r", "::@"]
la = ["log", "-s", "-r", "::"]
lb = ["log", "-s", "-r", "bookmarks()"]
lbt = ["log", "-s", "-r", "tags() | bookmarks()"]
lt = ["log", "-s", "-r", "tags()"]
lh = ["log", "-s", "-r", "heads(all())"]
ls = ["file", "list"]
f = ["file"]
gp = ["git", "push"]
gf = ["git", "fetch", "--all-remotes"]
gu = ["git", "fetch", "--all-remotes"]
n = ["new"]
r = ["rebase"]
rm = ["rebase-main"]
s = ["show"]
si = ["squash", "--interactive"]
sp = ["split"]
spi = ["split", "--interactive"]
sq = ["squash"]
ss = ["squash"]
tg = ["tug"]
t = ["tag"]
w = ["workspace"]
