#!/bin/bash
# this script links dotfiles from any directory to the home directory
[ $# -eq 0 ] && echo "$(basename $0) [-f|--force] DOTFILE(s)" && exit 1

force=
[ "${1}" = '-f' -o "${1}" = '--force' ] && force=1 && shift

while [ $# -ge 1 ]; do
	if [ -e $1 ]; then
		dest="$(basename $1)"
		if [ "${dest:0:1}" != '.' -a "${dest}" != 'bin' ]; then
			dest=".${dest}"
			echo "Prefixing destination name with a dot: ${dest}"
		fi
		if [ ! -e ~/"${dest}" -o -L ~/"${dest}" ] || [ -n "${force}" ]; then
			if [ -L ~/"${dest}" ]; then
				rm -v ~/"${dest}"
			fi
			ln -vfs "$PWD/$1" ~/"${dest}"
		else
			echo "The dotfile already exists: ~/${dest}"
		fi
	else
		echo "No such file or directory: $1"
	fi
	shift
done
