#!/bin/bash
# Synchronize cdargs directory list with mc's hotlist

if [[ ! -e ~/.cdargs ]]; then
	echo "Unable to find file ~/.cdargs." 1>&2
fi

if [[ ! -e ~/.config/mc/hotlist ]]; then
	mkdir -p ~/.config/mc
fi

while read n l; do
	if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
		continue
	fi
	echo "ENTRY \"${n}\" URL \"${l}\""
done < ~/.cdargs > ~/.config/mc/hotlist

if [ -d ~/.config/spacefm ]; then
	while read n l; do
		if [[ -z "${n}" ]] || [[ -z "${l}" ]]; then
			continue
		fi
		echo "file://${l} ${n}"
	done < ~/.cdargs > ~/.config/spacefm/bookmarks
fi

if [ -d ~/.cache/ctrlp ]; then
	mkdir -p ~/.cache/ctrlp/bkd
	sed -e 's/ /\t/' < ~/.cdargs > ~/.cache/ctrlp/bkd/cache.txt
fi
