"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"
# Defaults https://github.com/sxyazi/yazi/blob/d4924ebcad7125e2e7fc654ba017bd698d44af9b/yazi-config/preset/keymap-default.toml
# Config https://yazi-rs.github.io/docs/configuration/keymap/

# Unify keymaps between yazi and nnn
[[mgr.prepend_keymap]]
desc = "Edit file"
on = "e"
run = "open"

[[mgr.prepend_keymap]]
desc = "Enter directory"
on = "<Enter>"
run = "enter"

[[mgr.prepend_keymap]]
desc = "Leave directory"
on = "<Backspace>"
run = "leave"

[[mgr.prepend_keymap]]
desc = "Start interactive shell"
on = "!"
run = 'shell --block "$SHELL"'

# See https://github.com/stelcodes/bunny.yazi
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi"
on = ";"
run = "plugin bunny"

# Optionally, add another keymap to immediately fuzzy search bookmarks
[[mgr.prepend_keymap]]
desc = "Start bunny.yazi fuzzy search"
on = "'"
run = "plugin bunny fuzzy"
