wallpaper {
    monitor = DP-11
    path = ~/wallpaper2560x1440_3.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-9
    path = ~/wallpaper2560x1440_3.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-10
    path = ~/wallpaper2560x1440_2.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-8
    path = ~/wallpaper2560x1440_2.png
    fit_mode = cover
}

wallpaper {
    monitor =
    path = ~/wallpaper2560x1440.png
    fit_mode = cover
}
