# Documentation: https://wiki.hypr.land/Hypr-Ecosystem/hypridle/
general {
  # lock_cmd = "loginctl lock-session"
  lock_cmd = pidof hyprlock || hyprlock
  unlock_cmd = "loginctl unlock-session"
  on_lock_cmd = "hyprlock"
  before_sleep_cmd = "hyprlock"
}

listener {
  timeout = 600                                          # 10min.
  on-timeout = "loginctl lock-session"
}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}
