add_newline = true

[character]
symbol = "→"
vicmd_symbol = "[V](bold cyan)"
success_symbol = "[↳](bold cyan)"
error_symbol = "[✗](bold red)"

[cmd_duration]
show_notifications = true
min_time_to_notify = 30000

[directory]
truncation_symbol = "…/"

[git_branch]
always_show_remote = true
format = "on [$symbol$branch]($style)(:[$remote_name/$remote_branch]($style)) "
