add_newline = true

[character]
symbol = "→"
vicmd_symbol = "[V](bold cyan)"
success_symbol = "[↳](bold cyan)"
error_symbol = "[✗](bold red)"

[status]
style = "bold red"
disabled = false
symbol = ""
format = "[$symbol$status]($style) "

[cmd_duration]
show_notifications = true
min_time_to_notify = 30000

[directory]
truncation_symbol = "…/"

[git_branch]
always_show_remote = true
format = "on [$symbol$branch]($style)(:[$remote_name/$remote_branch]($style)) "

[git_status]
style = "bold purple"
untracked = "" # hide untracked status
ahead = "⇡$count"
behind = "⇣$count"
diverged = "⇕$ahead_count/$behind_count"

[custom.quilt_applied]
when = 'set -o pipefail; findfile patches | xargs -I {} test -e "{}/series"'
shell = ["sh"]
command = "quilt applied | wc -l | tr -d '\n'; echo -n '/'; quilt series | wc -l"
format = "[$symbol$output]($style)"
symbol = "🩹"
style = "bold blue"

# [custom.quilt_patches]
# when = 'set -o pipefail; findfile patches | xargs -I {} test -e "{}/series"'
# shell = ["sh"]
# command = "quilt series | wc -l"
# format = "/[$symbol$output]($style) "
# style = "bold blue"
