complete -c starship -n "__fish_use_subcommand" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_use_subcommand" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_use_subcommand" -f -a "init" -d 'Prints the shell function used to execute starship'
complete -c starship -n "__fish_use_subcommand" -f -a "prompt" -d 'Prints the full starship prompt'
complete -c starship -n "__fish_use_subcommand" -f -a "module" -d 'Prints a specific prompt module'
complete -c starship -n "__fish_use_subcommand" -f -a "config" -d 'Edit the starship configuration'
complete -c starship -n "__fish_use_subcommand" -f -a "toggle" -d 'Toggle a given starship module'
complete -c starship -n "__fish_use_subcommand" -f -a "bug-report" -d 'Create a pre-populated GitHub issue with information about your configuration'
complete -c starship -n "__fish_use_subcommand" -f -a "time" -d 'Prints time in milliseconds'
complete -c starship -n "__fish_use_subcommand" -f -a "explain" -d 'Explains the currently showing modules'
complete -c starship -n "__fish_use_subcommand" -f -a "timings" -d 'Prints timings of all active modules'
complete -c starship -n "__fish_use_subcommand" -f -a "completions" -d 'Generate starship shell completions for your shell to stdout'
complete -c starship -n "__fish_use_subcommand" -f -a "session" -d 'Generate random session key'
complete -c starship -n "__fish_use_subcommand" -f -a "help" -d 'Prints this message or the help of the given subcommand(s)'
complete -c starship -n "__fish_seen_subcommand_from init" -l print-full-init -d 'Print the main initialization script (as opposed to the init stub)'
complete -c starship -n "__fish_seen_subcommand_from init" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from init" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s s -l status -d 'The status code of the previously run command'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s p -l path -d 'The path that the prompt should render for.'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s P -l logical-path -d 'The logical path that the prompt should render for. This path should be a virtual/logical representation of the PATH argument.'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s d -l cmd-duration -d 'The execution duration of the last command, in milliseconds'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s k -l keymap -d 'The keymap of fish/zsh'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s j -l jobs -d 'The number of currently running jobs'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from prompt" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from module" -s s -l status -d 'The status code of the previously run command'
complete -c starship -n "__fish_seen_subcommand_from module" -s p -l path -d 'The path that the prompt should render for.'
complete -c starship -n "__fish_seen_subcommand_from module" -s P -l logical-path -d 'The logical path that the prompt should render for. This path should be a virtual/logical representation of the PATH argument.'
complete -c starship -n "__fish_seen_subcommand_from module" -s d -l cmd-duration -d 'The execution duration of the last command, in milliseconds'
complete -c starship -n "__fish_seen_subcommand_from module" -s k -l keymap -d 'The keymap of fish/zsh'
complete -c starship -n "__fish_seen_subcommand_from module" -s j -l jobs -d 'The number of currently running jobs'
complete -c starship -n "__fish_seen_subcommand_from module" -s l -l list -d 'List out all supported modules'
complete -c starship -n "__fish_seen_subcommand_from module" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from module" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from config" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from config" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from toggle" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from toggle" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from bug-report" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from bug-report" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from time" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from time" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from explain" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from explain" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from timings" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from timings" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from completions" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from completions" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from session" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from session" -s V -l version -d 'Prints version information'
complete -c starship -n "__fish_seen_subcommand_from help" -s h -l help -d 'Prints help information'
complete -c starship -n "__fish_seen_subcommand_from help" -s V -l version -d 'Prints version information'
