# See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# :r ./lazygit/themes-mergable/frappe/sapphire.yml

gui:
  theme:
    activeBorderColor:
      - "#85c1dc"
      - bold
    inactiveBorderColor:
      - "#a5adce"
    optionsTextColor:
      - "#8caaee"
    selectedLineBgColor:
      - "#414559"
    cherryPickedCommitBgColor:
      - "#51576d"
    cherryPickedCommitFgColor:
      - "#85c1dc"
    unstagedChangesColor:
      - "#e78284"
    defaultFgColor:
      - "#c6d0f5"
    searchingActiveBorderColor:
      - "#e5c890"

  authorColors:
    "*": "#babbf1"

# git:
#   paging:
#     colorArg: never
#     # pager: delta --dark --paging=never

services:
  gitlab.eucon-services.com: gitlab:gitlab.eucon-services.com
