# See https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md
# :r ./lazygit/themes/frappe.yml
frappe: &dark
  lightTheme: false
  activeBorderColor:
    - "#a6d189" # Green
    - bold
  inactiveBorderColor:
    - "#c6d0f5" # Text
  optionsTextColor:
    - "#8caaee" # Blue
  selectedLineBgColor:
    - "#414559" # Surface0
  selectedRangeBgColor:
    - "#414559" # Surface0
  cherryPickedCommitBgColor:
    - "#81c8be" # Teal
  cherryPickedCommitFgColor:
    - "#8caaee" # Blue
  unstagedChangesColor:
    - red # Red

# :r ./lazygit/themes/latte.yml
latte: &light
  lightTheme: true
  activeBorderColor:
    - "#40a02b" # Green
    - bold
  inactiveBorderColor:
    - "#4c4f69" # Text
  optionsTextColor:
    - "#1e66f5" # Blue
  selectedLineBgColor:
    - "#ccd0da" # Surface0
  selectedRangeBgColor:
    - "#ccd0da" # Surface0
  cherryPickedCommitBgColor:
    - "#179299" # Teal
  cherryPickedCommitFgColor:
    - "#1e66f5" # Blue
  unstagedChangesColor:
    - red # Red

gui:
  theme: *light
git:
  paging:
    colerArg: never
    # pager: delta --dark --paging=never
services:
  gitlab.eucon-services.com: gitlab:gitlab.eucon-services.com
