# Documentation: https://doc.rust-lang.org/cargo/reference/config.html

[build]
rustc-wrapper = "sccache" # speed up builds with a cache

[target.x86_64-unknown-linux-gnu]
linker = "clang" # the rust compiler tool
rustflags = [
  "-C",
  "link-arg=-fuse-ld=mold",
] # custom flags to pass to all compiler invocations
